import "bootstrap/dist/css/bootstrap.css";

import "./globals.css";
import BootstrapClient from "@/app/components/BootstrapClient";
import Banner from "./components/banner";
import Footer from "./components/footer";

export const metadata = {
  title: "Heritage Haven",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"bodyFontFamily"}>
        <Banner />
        {children}
        <Footer />
      </body>
      <BootstrapClient />
    </html>
  );
}
